name: medicine_label_scanner
description: A Flutter app for scanning and extracting text from medicine box labels
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Camera and image processing
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image: ^4.0.21
  http: ^1.2.0

  # Image picker for gallery upload
  image_picker: ^1.0.4

  # Permissions
  permission_handler: ^11.0.1

  # State management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.6

  # Barcode Scanner - Huawei HMS Scan Kit
  huawei_scan: ^2.12.0+304

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5  # Add this line
  flutter_lints: ^3.0.0

  # App launcher icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png


# ==================================================
# FLUTTER LAUNCHER ICONS CONFIGURATION
# ==================================================
flutter_launcher_icons:
  android: true
  ios: true

  image_path: assets/icon/logo_small.png

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/logo_small.png

  web:
    generate: true
    image_path: assets/icon/logo_small.png
    background_color: "#FFFFFF"
    theme_color: "#14B57F"
